// Normalize tech names to simple-icons slugs.
// https://simpleicons.org/ — CDN: https://cdn.simpleicons.org/<slug>
// Unknown names fall back to an initial chip in the UI.
const ICON_MAP: Record<string, string> = {
  "next.js": "nextdotjs",
  nextjs: "nextdotjs",
  next: "nextdotjs",
  supabase: "supabase",
  claude: "anthropic",
  "claude api": "anthropic",
  "claude code": "anthropic",
  anthropic: "anthropic",
  openai: "openai",
  gpt: "openai",
  chatgpt: "openai",
  vercel: "vercel",
  mapbox: "mapbox",
  typescript: "typescript",
  ts: "typescript",
  javascript: "javascript",
  js: "javascript",
  react: "react",
  "tailwind": "tailwindcss",
  "tailwind css": "tailwindcss",
  tailwindcss: "tailwindcss",
  postgres: "postgresql",
  postgresql: "postgresql",
  github: "github",
  node: "nodedotjs",
  "node.js": "nodedotjs",
  nodejs: "nodedotjs",
  python: "python",
  discord: "discord",
  stripe: "stripe",
  figma: "figma",
  docker: "docker",
  kubernetes: "kubernetes",
  redis: "redis",
  cloudflare: "cloudflare",
  aws: "amazonaws",
  "amazon web services": "amazonaws",
  gemini: "googlegemini",
  "google gemini": "googlegemini",
  slack: "slack",
  whatsapp: "whatsapp",
  telegram: "telegram",
  mongodb: "mongodb",
  prisma: "prisma",
  rust: "rust",
  go: "go",
  golang: "go",
  swift: "swift",
  "swiftui": "swift",
};

export function techIconSlug(name: string): string | null {
  const key = name.trim().toLowerCase();
  return ICON_MAP[key] ?? null;
}
